### ISSUE TITLE
Scrollview refreshcontrol not working

### ISSUE THREAD

**Issue by johnbioezone** [maphongba008/react-native-animated-header#3]
I implemented this library. As I expected all functions are working fine. But Scrollview refreshcontrol not working. Can you please help me?

**Comment by maphongba008** [comment]
Hi @johnbioezone, I just figure out the root cause of the issue but don't have any idea to fix it. The refresh control is there, but it was covered by the header.
The temporary solution is you should show a full screen loading hud when user refresh the list and dismiss when done.
Sorry for the inconvenience @johnbioezone. Let me know if you have any idea to resolve the issue. Thanks

**Comment by johnbioezone** [comment]
I found an solution. Used progressViewOffset property for Scrollview and refreshcontrol visible now.
